version: '3'

services:
  giraffechess:
    image: minordotnet.azurecr.io/giraffechess:latest
    environment:
      - VIRTUAL_HOST=giraffechess.netminor.infosupport.net
      - VIRTUAL_PORT=80
      - VIRTUAL_FOLDER=/
      - DB_CONN=Server=sql,1433;User Id=sa;Password=Geheim_101;Database=GiraffeChessDb;
    networks:
      - default
      - proxy
  sql:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Geheim_101
    networks:
      - default
networks:
  proxy:
    external:
      name: proxy_network